schema_version: 7
artifact_revision: 1
name: <your-project>
paths:
  streams: ./streams
  sources: ./sources
  datasets: ./datasets
  operations: ./operations
  artifacts: ../artifacts/${project_name}
  profiles: ./profiles
globals:
  # TODO: Set your sample cadence (must match ^\d+(m|min|h|d)$).
  cadence: 1h
  start_time: null
  end_time: null
