schema_version: 7
artifact_revision: 1
name: demo
paths:
  streams: ./streams
  sources: ./sources
  datasets: ./datasets
  operations: ./operations
  artifacts: ../artifacts/${project_name}
  profiles: ./profiles
globals:
  cadence: 1d
  start_time: 2021-01-01T00:00:00Z
  end_time: 2021-02-01T00:00:00Z
